using System;
using System.IO;
using System.Collections.Generic;
using System.Text;

namespace Wander.MetaConsole
{
  /// A class used for reading and writing variable archives files.
  public class ArchiveFile
  {
    string file;
    Dictionary<string, string> entries = new Dictionary<string, string>();

    public ArchiveFile(string fileName)
    {
      file = fileName;
      ReadEntries();
    }

    public void Set(string command, params string[] args)
    {
      // Join with quotes later.
      var value = String.Join(" ", args);
      if (entries.ContainsKey(command)) {
        entries[command] = value;
      } else {
        entries.Add(command, value);
      }
      WriteEntries(); // Not very performant to do this every time.
    }

    public bool ContainsEntry(string entry)
    {
      return entries.ContainsKey(entry);
    }

    public void Execute()
    {
      foreach(var entry in entries) {
        string command = entry.Key + " " + entry.Value;
        CommandLine.Execute(command);
      }
    }

    void ReadEntries()
    {
      entries.Clear();
      var inputs = File.ReadAllText(file).Split('\n');
      foreach (var input in inputs) {
        if (input.StartsWith("#")) continue;
        var tokens = input.Split(new char[] { ' ' }, 2);
        if (tokens.Length != 2) continue; // Skip this one, archive incorrectly.
        entries.Add(tokens[0], tokens[1]);        
      }
    }

    void WriteEntries()
    {
      var str = new StringBuilder();
      str.AppendLine("# Autogenerated archive file, do not modify.");
      foreach (var entry in entries) {
        str.AppendFormat("{0} {1}\n", entry.Key, entry.Value);
      }
      File.WriteAllText(file, str.ToString());
    }
  }
}